version: 0.0
os: linux
files: 
  - source: /
    destination: /home/ubuntu/hogwarts
permissions:
  - object: /home/ubuntu/hogwarts
    pattern: "*"
    owner: ubuntu
    group: ubuntu
    type: 
      - file
  - object: /home/ubuntu/hogwarts
    owner: ubuntu
    group: ubuntu
    type: 
      - directory
hooks:
  BeforeInstall:
      - location: scripts/clean_instance.sh
        timeout: 300
        runas: ubuntu
      
  AfterInstall:
      - location: scripts/set_permissions.sh
        timout: 300
        runas: ubuntu
      - location: scripts/setup_env.sh
        timout: 300
        runas: ubuntu
      - location: scripts/instance_os_dependencies.sh
        timeout: 300
        runas: ubuntu
      - location: scripts/python_dependencies.sh
        timeout: 300
        runas: ubuntu
      - location: scripts/gunicorn.sh
        timeout: 300
        runas: ubuntu
      - location: scripts/nginx.sh
        timeout: 300
        runas: ubuntu
  ApplicationStop:
      - location: scripts/stop_app.sh
        timeout: 300
        runas: ubuntu
  ApplicationStart:
      - location: scripts/start_app.sh
        timeout: 300
        runas: ubuntu
  
  