# Generated by Django 4.1.2 on 2023-07-29 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_alter_doctor_user_alter_practice_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='rating',
            field=models.FloatField(default=3),
        ),
    ]
